env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: 
  react/jsx-props-no-spreading: 
    - off
  no-plusplus: 
    - off
  no-param-reassign:
    - off
  react/prop-types:
    - off
  no-nested-ternary: 
    - off
  no-unused-vars:
    - off
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .tsx
      - .ts

